-- Animal_ins Table

-- NAME	TYPE	NULLABLE
-- ANIMAL_ID	VARCHAR(N)	FALSE
-- ANIMAL_TYPE	VARCHAR(N)	FALSE
-- DATETIME	DATETIME	FALSE
-- INTAKE_CONDITION	VARCHAR(N)	FALSE
-- NAME	VARCHAR(N)	TRUE
-- SEX_UPON_INTAKE	VARCHAR(N)	FALSE

-- Result

-- A349996	Sugar
-- A350276	Jewel
-- A350375	Meo
-- A352555	Harley
-- A352713	Gia
-- A352872	Peanutbutter
-- A353259	Bj

SELECT ANIMAL_ID, NAME
  FROM ANIMAL_INS
 ORDER BY ANIMAL_ID ASC;