-- ANIMAL_OUTS

-- NAME	TYPE	NULLABLE
-- ANIMAL_ID	VARCHAR(N)	FALSE
-- ANIMAL_TYPE	VARCHAR(N)	FALSE
-- DATETIME	DATETIME	FALSE
-- NAME	VARCHAR(N)	TRUE
-- SEX_UPON_OUTCOME	VARCHAR(N)	FALSE

-- Result

-- HOUR	COUNT
-- 9	1
-- 10	2
-- 11	13
-- 12	10
-- 13	14
-- 14	9
-- 15	7
-- 16	10
-- 17	12
-- 18	16
-- 19	2

SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')), COUNT(*)
  FROM ANIMAL_OUTS
 GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
 HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) >= 9
     AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) <=19
 ORDER BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'));