-- Animal_ins Table

-- NAME	TYPE	NULLABLE
-- ANIMAL_ID	VARCHAR(N)	FALSE
-- ANIMAL_TYPE	VARCHAR(N)	FALSE
-- DATETIME	DATETIME	FALSE
-- INTAKE_CONDITION	VARCHAR(N)	FALSE
-- NAME	VARCHAR(N)	TRUE
-- SEX_UPON_INTAKE	VARCHAR(N)	FALSE

-- Result

-- NAME	COUNT
-- Lucy	3
-- Raven	2

SELECT NAME, COUNT(*)
  FROM ANIMAL_INS
 WHERE NAME IS NOT NULL
 GROUP BY NAME
 HAVING COUNT(*) >=2
 ORDER BY NAME;
